In [1]:
import regex as re
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
from numpy import random
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
import pandas as pd
from Preprocessing import *

C:\Users\user\anaconda3\envs\tf3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [76]:
class models:
    
    def __init__(self, train_x, train_y, dev_x = None, dev_y = None, test_x = None, test_y = None):
        self.train_x = train_x
        self.train_y = train_y
        
        self.dev_x = dev_x
        self.dev_y = dev_y
           
        self.test_x = test_x
        self.test_y = test_y
        
        self.Word2Vec = None
        self.MaxEnt = None
        
        
    def set_train_data(self, train_x, train_y):
        
        self.train_x = train_x
        self.train_y = train_y
        
    def set_test_data(self, test_x, test_y):
        
        self.test_x = test_x
        self.test_y = test_y
        
    def set_dev_data(self, dev_x, dev_y):
        
        self.dev_x = dev_x
        self.dev_y = dev_y
        
        
    def train_Word2Vec(self):
        tagged_docs = [TaggedDocument(words = x, tags = str(y)) for x in self.train_x for y in self.train_y]
        
        x_merged = []
        
        for lst in self.train_x:
            x_merged.extend(lst)
        
        x_dict = {x: x_merged.count(x) for x in set(x_merged)}
        model_dm = Doc2Vec(dm = 1, vector_size = 300, epochs = 50)
        model_dm.build_vocab_from_freq(x_dict)
        model_dm.train(tagged_docs, total_examples=len(tagged_docs), epochs=model_dm.epochs)
        
        self.Word2Vec = model_dm
        
    
    def train_MaxEnt(self):
        
        assert self.Word2Vec is not None, "ERROR: Word2Vec model not initialized yet! Call models.Word2Vec() to initialize."
        
        train_x_vectorized = [self.Word2Vec.infer_vector(x) for x in train_x]
        
        logreg = LogisticRegression(max_iter = 1000, C=1e5)
        logreg.fit(train_x_vectorized, train_y)
        
        self.MaxEnt = logreg
        
    def test
        
        
        
    

In [77]:
train_x_vectorized = [model_dm.infer_vector(x) for x in train_x]

In [78]:
logreg = LogisticRegression(max_iter = 1000, C=1e5)
logreg.fit(train_x_vectorized, train_y)

LogisticRegression(C=100000.0, max_iter=1000)

In [111]:
for x in range(0, len(test_x)):
    #print(logreg.predict_proba(model_dm.infer_vector(x).reshape(1, -1)))
    x_vec = model_dm.infer_vector(test_x[x]).reshape(1, -1)
    print(logreg.predict(x_vec))
    predict = logreg.predict_proba(x_vec)
    print(np.argmax(predict))
    actual = test_y[x]
                             
    print(predict, ' ', actual)
    log_predict = logreg.predict_log_proba(x_vec)[0]
    print(log_predict)
    for value in log_predict:
        print(np.around(value, decimals = 5))
    
    print(np.around(predict[0][0], decimals = 5))
    print(np.around(predict[0][1], decimals = 5))
    
    print(predict[0][1] < 0.00001)
    print('______')

[1]
1
[[4.08588891e-04 9.99591411e-01]]   0
[-7.80280106e+00 -4.08672386e-04]
-7.8028
-0.00041
0.00041
0.99959
False
______
[0]
0
[[0.66317791 0.33682209]]   0
[-0.41071199 -1.08820041]
-0.41071
-1.0882
0.66318
0.33682
False
______
[0]
0
[[1.00000000e+00 1.89134676e-12]]   0
[-1.89137594e-12 -2.69937320e+01]
-0.0
-26.99373
1.0
0.0
True
______
[0]
0
[[1.00000000e+00 2.12948654e-12]]   0
[-2.12951878e-12 -2.68751402e+01]
-0.0
-26.87514
1.0
0.0
True
______
[0]
0
[[1.00000000e+00 9.01047319e-11]]   0
[-9.01047015e-11 -2.31300484e+01]
-0.0
-23.13005
1.0
0.0
True
______
[0]
0
[[0.99216911 0.00783089]]   0
[-0.00786172 -4.84967867]
-0.00786
-4.84968
0.99217
0.00783
False
______
[0]
0
[[1.00000000e+00 2.05544826e-23]]   0
[  0.         -52.23896319]
0.0
-52.23896
1.0
0.0
True
______
[1]
1
[[8.20550849e-04 9.99179449e-01]]   0
[-7.10553468e+00 -8.20887685e-04]
-7.10553
-0.00082
0.00082
0.99918
False
______
[0]
0
[[9.99928373e-01 7.16268789e-05]]   0
[-7.16294443e-05 -9.54404015e+00]
-7e-05
-9.5

C:\Users\user\anaconda3\envs\tf3\lib\site-packages\sklearn\linear_model\_logistic.py:1499: RuntimeWarning: divide by zero encountered in log
  return np.log(self.predict_proba(X))
C:\Users\user\anaconda3\envs\tf3\lib\site-packages\sklearn\linear_model\_logistic.py:1499: RuntimeWarning: divide by zero encountered in log
  return np.log(self.predict_proba(X))


In [109]:
logreg. decision_function(model_dm.infer_vector(['5G', 'causes', 'covid']).reshape(1, -1))

array([14.57798248])

In [102]:
print(type(model_dm.infer_vector(['5G', 'causes', 'covid'])))

<class 'numpy.ndarray'>
